FROM python:3.8
ENV PYTHONUNBUFFERED=1
WORKDIR  /usr/src/app
COPY requirements.txt /usr/src/app
RUN apt-get update
RUN apt-get install -y --no-install-recommends \
    gcc libgraphviz-dev default-libmysqlclient-dev gdal-bin libgdal-dev
RUN pip install -r requirements.txt