# Generated by Django 3.2.9 on 2021-11-21 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deers', to='area.area')),
            ],
            options={
                'db_table': 'deer',
            },
        ),
        migrations.RemoveField(
            model_name='boardinglog',
            name='ek_scooter',
        ),
        migrations.DeleteModel(
            name='EKScooter',
        ),
        migrations.AddField(
            model_name='boardinglog',
            name='deer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boarding_logs', to='vehicle.deer'),
        ),
    ]
