# Generated by Django 3.2.9 on 2021-11-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_auto_20211121_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardinglog',
            name='fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boardinglog',
            name='use_end_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='boardinglog',
            name='use_end_lat',
            field=models.DecimalField(decimal_places=14, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='boardinglog',
            name='use_end_lng',
            field=models.DecimalField(decimal_places=14, max_digits=17, null=True),
        ),
    ]
