# Generated by Django 3.2.9 on 2021-11-19 10:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_boundary', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('area_center', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('area_coords', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
                ('basic_fee', models.IntegerField()),
                ('fee_per_min', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'area',
            },
        ),
    ]
